<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>~*~* Rudy's Epic Corner *~*~</title>
  <style>
    body {
      font-family: "Comic Sans MS", cursive, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #000000;
      background-image: url("/api/placeholder/100/100");
      display: flex;
      justify-content: center;
      padding-top: 30px;
      color: #FFFFFF;
      cursor: url("/api/placeholder/32/32"), auto;
    }
    
    .container {
      width: 800px;
      border: 3px solid #00FFFF;
      overflow: hidden;
      box-shadow: 0 0 15px #00FFFF;
    }
    
    .header {
      background-color: #ff3333;
      color: yellow;
      padding: 15px;
      text-align: center;
      font-weight: bold;
      font-size: 24px;
      position: relative;
      border-bottom: 3px dashed #FFFF00;
      text-shadow: 2px 2px #000000;
    }
    
    .fire-gif {
      height: 30px;
      vertical-align: middle;
      margin: 0 10px;
    }
    
    .content {
      background-color: #000033;
      padding: 20px;
      min-height: 200px;
      position: relative;
      background-image: url("/api/placeholder/50/50");
    }
    
    .footer {
      background-color: #990000;
      color: #FFFF00;
      padding: 15px;
      line-height: 1.5;
      border-top: 3px dashed #FFFF00;
      text-shadow: 1px 1px #000000;
    }
    
    .what-im-up-to {
      color: #FF00FF;
      font-weight: bold;
      margin-left: 30px;
      margin-top: 20px;
      text-decoration: underline;
      cursor: pointer;
      font-size: 18px;
      text-shadow: 2px 2px #000000;
      animation: blink 1s infinite;
    }
    
    @keyframes blink {
      0% { opacity: 1; }
      50% { opacity: 0.5; }
      100% { opacity: 1; }
    }
    
    .kickflip-image {
      float: right;
      width: 150px;
      height: 100px;
      border: 5px ridge #FF00FF;
      margin-right: 50px;
      image-rendering: pixelated;
    }
    
    .visitor-counter {
      text-align: center;
      margin-top: 20px;
      font-size: 12px;
      color: #FFFFFF;
      background-color: #333333;
      padding: 5px;
      border: 1px solid #FFFFFF;
      width: 200px;
      margin-left: auto;
      margin-right: auto;
    }
    
    marquee {
      background-color: #000000;
      color: #00FF00;
      padding: 5px;
      font-weight: bold;
    }
    
    .buttons {
      display: flex;
      justify-content: center;
      margin-top: 20px;
      flex-wrap: wrap;
      gap: 10px;
    }
    
    .button {
      background-color: #666666;
      border: 2px outset #999999;
      color: #FFFFFF;
      padding: 3px 8px;
      font-size: 12px;
      text-decoration: none;
      text-align: center;
    }
    
    .divider {
      height: 20px;
      background: url("/api/placeholder/20/20") repeat-x;
      margin: 10px 0;
    }
    
    .under-construction {
      text-align: center;
      margin: 20px 0;
    }
    
    .guestbook {
      margin-top: 15px;
      border: 1px dashed #FFFFFF;
      padding: 10px;
      font-size: 14px;
    }
    
    .guestbook-title {
      font-weight: bold;
      text-align: center;
      margin-bottom: 10px;
      color: #FFFF00;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      ~*~* Rudy's Epic Corner *~*~
      <br>
      <img src="https://i.gifer.com/WMDw.gif" class="fire-gif" alt="fire gif">
      <img src="https://i.gifer.com/WMDw.gif" class="fire-gif" alt="fire gif">
      <img src="https://i.gifer.com/WMDw.gif" class="fire-gif" alt="fire gif">
      <img src="https://i.gifer.com/WMDw.gif" class="fire-gif" alt="fire gif">
      <img src="https://i.gifer.com/WMDw.gif" class="fire-gif" alt="fire gif">
    </div>
    
    <marquee scrollamount="9" direction="left">Welcome to my totally awesome website! Only stay if cool!</marquee>
    
    <div class="content">
      <a href="https://www.fbi.gov/wanted" class="what-im-up-to">
        What I'm Up to! B)
      </a>
      
      <a href="https://gyazo.com/bcfaa4d3838362bd23c0bb700da1af26"><img src="https://i.gyazo.com/bcfaa4d3838362bd23c0bb700da1af26.webp" alt="Image from Gyazo" width="200"/></a>
      
      <div class="under-construction">
        <img src="/api/placeholder/40/40" alt="Under Construction">
        UNDER CONSTRUCTION
        <img src="/api/placeholder/40/40" alt="Under Construction">
      </div>
      
      <div class="divider"></div>
      
      <div class="buttons">
        <a href="#" class="button">HOME</a>
        <a href="#" class="button">MY PICS</a>
        <a href="#" class="button">FAVORITE LINKS</a>
        <a href="#" class="button">GUESTBOOK</a>
        <a href="#" class="button">EMAIL ME</a>
      </div>
      
      <div class="guestbook">
        <div class="guestbook-title">MY GUESTBOOK - SIGN IT OR ELSE!</div>
        Wappaa87: omg cool site!!! <br>
        shootokillgaming12: nice kickflip bro <br>
        AtothaK: how to delete search history. google. google.com. why computer not wokring <br>
        SuprSAM: rolf ^ @AtothaK u r sending stuff not looking it up <br>
        JuJuLaLa: lol u guys arent using The FaceBook yet? <br>
        MerBear_1: does anyone else know how to get the best horse in starstables???
      </div>
      
      <div class="visitor-counter">
        You are visitor number: 0007
      </div>
    </div>
    
    <div class="footer">
      Yo whats up! My name is Rudy, but you can call me R dawg! I like cars, skateboarding, paw patrol, and really anything thats cool. If you're also kewl, send me a message at X_HARDR_X@myspace.com
      <br><br>
      Smella ya later!
      <br><br>
      <div style="text-align: center; font-size: 10px;">
        © 2007 Rudy's Epic Corner | Last updated: 06/15/2007 | This site is best viewed with Internet Explorer
      </div>
    </div>
  </div>
</body>
</html>
